# Generated by Django 6.0.5 on 2026-05-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementscontrol',
            options={'verbose_name': 'Элемент контроля', 'verbose_name_plural': 'Элементы контроля'},
        ),
        migrations.AlterModelOptions(
            name='postfromuser',
            options={'verbose_name': 'Пост пользователя', 'verbose_name_plural': 'Посты пользователей'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='roleaccess',
            options={'verbose_name': 'Доступ роли', 'verbose_name_plural': 'Доступы ролей'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
