# Generated by Django 6.0.5 on 2026-05-24 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_alter_elementscontrol_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementscontrol',
            options={'verbose_name': 'Элемент управления', 'verbose_name_plural': 'Элементы управления'},
        ),
        migrations.AlterModelOptions(
            name='roleaccess',
            options={'verbose_name': 'Право доступа роли', 'verbose_name_plural': 'Права доступа ролей'},
        ),
        migrations.AlterField(
            model_name='elementscontrol',
            name='element_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя контролируемого элемента'),
        ),
        migrations.AlterField(
            model_name='postfromuser',
            name='content',
            field=models.TextField(verbose_name='Содержимое поста'),
        ),
        migrations.AlterField(
            model_name='postfromuser',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='postfromuser',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок поста'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название роли'),
        ),
        migrations.AlterField(
            model_name='roleaccess',
            name='can_create',
            field=models.BooleanField(default=False, verbose_name='Cоздание (Create)'),
        ),
        migrations.AlterField(
            model_name='roleaccess',
            name='can_delete_all',
            field=models.BooleanField(default=False, verbose_name='Удаление всех (Delete All)'),
        ),
        migrations.AlterField(
            model_name='roleaccess',
            name='can_delete_own',
            field=models.BooleanField(default=False, verbose_name='Удаление своих (Delete Own)'),
        ),
        migrations.AlterField(
            model_name='roleaccess',
            name='can_read_all',
            field=models.BooleanField(default=False, verbose_name='Чтение всех (Read All)'),
        ),
        migrations.AlterField(
            model_name='roleaccess',
            name='can_read_own',
            field=models.BooleanField(default=False, verbose_name='Чтение своих (Read Own)'),
        ),
        migrations.AlterField(
            model_name='roleaccess',
            name='can_update_all',
            field=models.BooleanField(default=False, verbose_name='Модификация всех (Update All)'),
        ),
        migrations.AlterField(
            model_name='roleaccess',
            name='can_update_own',
            field=models.BooleanField(default=False, verbose_name='Модификация своих (Update Own)'),
        ),
        migrations.AlterField(
            model_name='roleaccess',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='Forum.elementscontrol', verbose_name='Элемент'),
        ),
        migrations.AlterField(
            model_name='roleaccess',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='Forum.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Электронная почта (Email)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fathername',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль (хэш)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='Forum.role', verbose_name='Роль'),
        ),
    ]
